language: node_js

node_js:
  - 'node'
  - '12'
  - '9.11.2'

matrix:
  fast_finish: true

branches:
  only:
  - main
  - /^release-.*/

script:
  - npm test

cache:
  directories:
    - node_modules

git:
  depth: 1