language: node_js

node_js:
  - '14'
  - '12'
  - '10'

matrix:
  fast_finish: true

branches:
  only:
  - main
  - /^release-.*/

script:
  - npm test

cache:
  directories:
    - node_modules

git:
  depth: 1