language: node_js

node_js:
  - 'node'
  - '12'

matrix:
  fast_finish: true

branches:
  only:
  - main
  - /^release-.*/

script:
  - npm run test

cache:
  directories:
    - node_modules

git:
  depth: 1