language: node_js

node_js:
  - 'node'
  - '12'
  - '9'

matrix:
  fast_finish: true

branches:
  only:
  - main
  - /^release-.*/

install:
  - npm install 
  
script:
  - npm run test

cache:
  directories:
    - node_modules

git:
  depth: 1